# Bootloader selection
BOOTLOADER = atmel-dfu

AUTO_SHIFT_ENABLE      = no
BOOTMAGIC_ENABLE       = yes
CAPS_WORD_ENABLE       = yes
COMBO_ENABLE           = yes
COMMAND_ENABLE         = no
CONSOLE_ENABLE         = no
EXTRAKEY_ENABLE	       = yes
GRAVE_ESC_ENABLE       = no
KEY_OVERRIDE_ENABLE    = no
LTO_ENABLE             = yes
MAGIC_ENABLE           = no
MOUSEKEY_ENABLE        = yes
MUSIC_ENABLE           = no
NKRO_ENABLE            = yes
NO_USB_STARTUP_CHECK   = yes
OLED_ENABLE            = no
RGB_MATRIX_ENABLE      = no
RGBLIGHT_ENABLE        = no
SPACE_CADET_ENABLE     = no
SPLIT_KEYBOARD         = yes
TAP_DANCE_ENABLE       = yes
VIA_ENABLE             = yes
VIAL_ENABLE            = yes
